name: brote_cero
description: Lector vertical de historias del universo Brote Cero.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  google_mobile_ads: 5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/story/001/
    - assets/story/002/
